## below a list of packages that we will need for the practical sessions of this course
## make sure that you have them installed in your local R environment

library("DT")
library("fpp")
library("plm")
library("fpp2")
library("broom")
library("knitr")
library("sommer")
library("ggpubr")
library("lmtest")
library("GGally")
library("xgboost")
library("tseries")
library("ggplot2")
library("corrplot")
library("forecast")
library("contrast")
library("survival")
library("MLmetrics")
library("survminer")
library("lubridate")
library("tidyverse")
library("tidymodels")
library("data.table")
